apiVersion: v1
kind: Service
metadata:
  name: "${WEB_SERVICE_NAME@microservice-blog-config}"
  namespace: "${NAMESPACE@microservice-config}"
  labels:
    moduleid: microservice-blog-realm
    version: 1.70.4-master
spec:
  type: NodePort
  selector:
    app: "${WEB_DEPLOYMENT_NAME}"
  ports:
    - name: port
      port: "${WEB_INTERNAL_PORT@microservice-blog-config}"
